import os
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


def ensure_directory_exists(directory):
    """Ensure the specified directory exists, creating it if necessary."""
    if not os.path.exists(directory):
        os.makedirs(directory)


def save_plot(filename, func, *args, **kwargs):
    """Save a plot generated by a given function to a specified filename."""
    ensure_directory_exists(os.path.dirname(filename))
    plt.figure()
    func(*args, **kwargs)
    plt.savefig(filename)
    plt.close()


def plot_stats_year(stats, situation, color):
    """Plot statistics of doctoral students by year for a specific situation."""
    stats.sort(key=lambda x: x["premiere_inscription__year"])
    filtered_stats = [stat for stat in stats if stat.get("situation") == situation]

    years = [stat["premiere_inscription__year"] for stat in filtered_stats]
    totals = [stat["total"] for stat in filtered_stats]

    plt.bar(years, totals, color=color)
    plt.xlabel("Année")
    plt.ylabel(f"Nombre de Doctorants {situation}")
    plt.title(f"Statistiques des Doctorants {situation} par Année")
    plt.xticks(years)
    plt.grid(axis="y")


def plot_stats_situation_year(stats, year):
    """Plot statistics of doctoral students for different situations in a specific year."""
    stats_for_year = [
        stat for stat in stats if stat["premiere_inscription__year"] == year
    ]

    situations = ["Inscrit", "Soutenu", "Abandon"]
    totals = [
        sum(stat["total"] for stat in stats_for_year if stat["situation"] == situation)
        for situation in situations
    ]

    plt.bar(situations, totals, color=["blue", "green", "red"])
    plt.xlabel("Situation")
    plt.ylabel("Nombre de Doctorants")
    plt.title(f"Statistiques pour l'année {year}")
    plt.grid(axis="y")


def plot_stats_sexe(stats):
    """Plot statistics of doctoral students by sex for all enrolled students."""
    total_F = sum(stat["total"] for stat in stats if stat["sexe"] == "F")
    total_M = sum(stat["total"] for stat in stats if stat["sexe"] == "M")

    sexes = ["F", "M"]
    totals = [total_F, total_M]
    colors = ["pink", "blue"]

    plt.bar(sexes, totals, color=colors)
    plt.xlabel("Sexe")
    plt.ylabel("Nombre de Doctorants Inscrits")
    plt.title("Statistiques par Sexe (Inscrits seulement)")
    plt.xticks(sexes)
    plt.grid(axis="y")


def plot_stats_sexe_year(stats, year):
    """Plot statistics of doctoral students by sex for a specific year."""
    stats_for_year = [
        stat for stat in stats if stat["premiere_inscription__year"] == year
    ]

    total_F = sum(stat["total"] for stat in stats_for_year if stat["sexe"] == "F")
    total_M = sum(stat["total"] for stat in stats_for_year if stat["sexe"] == "M")

    sexes = ["F", "M"]
    totals = [total_F, total_M]
    colors = ["pink", "blue"]

    plt.bar(sexes, totals, color=colors)
    plt.xlabel("Sexe")
    plt.ylabel("Nombre de Doctorants Inscrits")
    plt.title(f"Statistiques par Sexe pour l'année {year}")
    plt.xticks(sexes)
    plt.grid(axis="y")


def plot_stats_specialite(stats):
    """Plot statistics of doctoral students by specialty for all enrolled students."""
    specialites = list(set(stat["specialite"] for stat in stats))
    totals = [
        sum(stat["total"] for stat in stats if stat["specialite"] == specialite)
        for specialite in specialites
    ]

    plt.bar(specialites, totals)
    plt.xlabel("Spécialité")
    plt.ylabel("Nombre de Doctorants Inscrits")
    plt.title("Statistiques par Spécialité (Inscrits seulement)")
    plt.grid(axis="y")


def plot_stats_specialite_year(stats, year):
    """Plot statistics of doctoral students by specialty for a specific year."""
    stats_for_year = [
        stat for stat in stats if stat["premiere_inscription__year"] == year
    ]

    specialites = list(set(stat["specialite"] for stat in stats_for_year))
    totals = [
        sum(stat["total"] for stat in stats_for_year if stat["specialite"] == specialite)
        for specialite in specialites
    ]
    colors = ["blue", "orange", "green"]

    plt.bar(specialites, totals, color=colors)
    plt.xlabel("Spécialité")
    plt.ylabel("Nombre de Doctorants Inscrits")
    plt.title(f"Statistiques par Spécialité pour l'année {year}")
    plt.grid(axis="y")
