# Generated by Django 5.1.1 on 2024-10-07 12:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('ville', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotCle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mot_cle', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('Google Scholar', 'Google Scholar'), ('ResearchGate', 'ResearchGate'), ('Classified', 'Classified'), ('Autre', 'Autre')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pays', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctorant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, max_length=10, null=True)),
                ('fonction', models.CharField(blank=True, max_length=255, null=True)),
                ('emails', models.JSONField(blank=True, default=list, null=True)),
                ('telephones', models.JSONField(blank=True, default=list, null=True)),
                ('type_doctorat', models.CharField(choices=[('LMD', 'LMD (5 years)'), ('Classique', 'Classique (6 years)')], max_length=50)),
                ('premiere_inscription', models.DateField(blank=True, null=True)),
                ('titre_these', models.TextField(blank=True, null=True)),
                ('date_enregistrement_these', models.DateField(blank=True, null=True)),
                ('specialite', models.CharField(blank=True, max_length=100, null=True)),
                ('situation', models.CharField(choices=[('Inscrit', 'Inscrit'), ('Soutenu', 'Soutenu'), ('Abandon', 'Abandon')], default='Inscrit', max_length=50)),
                ('date_soutenance_pv_abandon', models.DateField(blank=True, null=True)),
                ('annee_etude', models.IntegerField(default=1)),
                ('etablissement_exercice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctorants_exercice', to='database.etablissement')),
                ('etablissement_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctorants_origine', to='database.etablissement')),
                ('etablissement_origine_graduation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctorants_graduation', to='database.etablissement')),
                ('etablissement_origine_magister', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctorants_magister', to='database.etablissement')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_evaluation', models.DateField()),
                ('statut', models.CharField(choices=[('Admis', 'Admis'), ('Non admis', 'Non admis')], default='Non admis', max_length=50)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('doctorant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='database.doctorant')),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('grade', models.CharField(choices=[('MCA', 'MCA'), ('PR', 'PR')], max_length=50)),
                ('emails', models.JSONField(blank=True, default=list, null=True)),
                ('telephones', models.JSONField(blank=True, default=list, null=True)),
                ('nombre_expertises', models.IntegerField(default=0)),
                ('nombre_publications', models.IntegerField(default=0)),
                ('etablissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experts_etablissement', to='database.etablissement')),
                ('mots_cles', models.ManyToManyField(blank=True, related_name='experts_mots_cles', to='database.motcle')),
            ],
        ),
        migrations.AddField(
            model_name='doctorant',
            name='co_directeur_these',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctorants_co_directeurs', to='database.expert'),
        ),
        migrations.AddField(
            model_name='doctorant',
            name='directeur_these',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctorants_directeurs', to='database.expert'),
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avis_expert_1', models.CharField(choices=[('Favorable', 'Favorable'), ('Favorable sous réserve', 'Favorable sous réserve'), ('Défavorable', 'Défavorable')], max_length=50)),
                ('avis_expert_2', models.CharField(choices=[('Favorable', 'Favorable'), ('Favorable sous réserve', 'Favorable sous réserve'), ('Défavorable', 'Défavorable')], max_length=50)),
                ('avis_expert_3', models.CharField(blank=True, choices=[('Favorable', 'Favorable'), ('Favorable sous réserve', 'Favorable sous réserve'), ('Défavorable', 'Défavorable')], max_length=50, null=True)),
                ('commentaire_expert_1', models.TextField(blank=True, null=True)),
                ('commentaire_expert_2', models.TextField(blank=True, null=True)),
                ('commentaire_expert_3', models.TextField(blank=True, null=True)),
                ('date_expertise', models.DateField()),
                ('doctorant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertises', to='database.doctorant')),
                ('expert_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertises_as_expert_1', to='database.expert')),
                ('expert_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertises_as_expert_2', to='database.expert')),
                ('expert_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expertises_as_expert_3', to='database.expert')),
            ],
        ),
        migrations.AddField(
            model_name='doctorant',
            name='laboratoires',
            field=models.ManyToManyField(blank=True, related_name='doctorants', to='database.laboratoire'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etablissements', to='database.pays'),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.TextField()),
                ('source', models.CharField(choices=[('Google Scholar', 'Google Scholar'), ('ResearchGate', 'ResearchGate'), ('DBLP', 'DBLP'), ('Autre', 'Autre')], max_length=50)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='database.expert')),
            ],
        ),
        migrations.CreateModel(
            name='PV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annee', models.IntegerField()),
                ('pv_document', models.TextField()),
                ('doctorant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvs', to='database.doctorant')),
            ],
        ),
    ]
